#!/bin/sh
## Tool :: dnsx
## Description :: Look for the A records for a given host list
## Global Variables
d=$(date +"%Y%m%d")
t=$(date +"%H%M")
s=$2
domains=$1
##
##
cd /tmp;
/asm/tools/dnsx -t 10 -r 1.1.1.1,9.9.9.9,208.67.222.222 -soa -duc -silent -l $domains -j -o dnsx.soa.$d.$t.json
mv dnsx.soa.$d.$t.json /asm/output/dnsx/
##
##
sleep 1;
/asm/tools/dnsx -t 10 -r 8.8.8.8 -mx -l $domains -duc -silent -j -o dnsx.mx.$d.$t.json
mv dnsx.mx.$d.$t.json /asm/output/dnsx/
##
##
sleep 2;
/asm/tools/dnsx -t 10 -r 1.1.1.1 -ns -duc -silent -l $domains -j -o dnsx.ns.$d.$t.json
mv dnsx.ns.$d.$t.json /asm/output/dnsx/
##
##
