#!/bin/sh
## Tool :: whatweb
## Description :: take results and scan for the clear text version.
## Global Variables
d=$(date +"%Y%m%d")
t=$(date +"%H%M")
s=$2
hosts=$1
cd /tmp; sleep 1; echo "";
###########
##
##
for i in $(ls -aln /asm/output/host/host.a.* | tail -n 4 | awk '{print $9}'); do 
	cat $i | grep -v ", ," | cut -f1 -d"," >> /tmp/host.$d.$t.ww.tmp
done
echo ""

echo ""; echo "Starting our scans.";
for i in $(shuf -n 200 /tmp/host.$d.$t.ww.tmp ); do 
  	whatweb --no-errors --url-prefix http:// --wait=2 --follow-redirect=same-site --log-json=$i.json --user-agent="Mozilla/5.1 (compatible;  MSIEISRT Linux CHASM)" $i;
	cat $i.json | jq >> whatweb.http.$d.$t.$s.json
	echo "" >> whatweb.http.$d.$t.$s.json
	rm -rf $i.json
done
mv whatweb.http.$d.$t.$s.json /asm/output/whatweb/
rm -rf /tmp/msie.scanww.all; sleep 1;
rm /tmp/msie.scanww.tmp; sleep 1; echo "done";
##
# EOF
